### ISSUE TITLE
Please keep this up :( 

### ISSUE THREAD

**Issue by erikhric** [schmittx/homebridge-homeassistant#20]
Hi all,
I don't know if you realise, but this plugin helps you control Homeassistant devices via Alexa for free!!!
The original Alexa Skill for Homeassistant requires you to pay for their Cloud.
If you combine this plugin with alexa for homebridge you have it for free.
https://www.npmjs.com/package/homebridge-alexa

BTW - I have this error for my sensor:

`/usr/lib/node_modules/homebridge-homeassistant-schmittx/accessories/device_tracker.js:9
  this.data = data;
            ^
TypeError: Cannot set property 'data' of undefined
    at HomeAssistantDeviceTracker (/usr/lib/node_modules/homebridge-homeassistant-schmittx/accessories/device_tracker.js:9:13)
    at request (/usr/lib/node_modules/homebridge-homeassistant-schmittx/index.js:183:25)
    at Request.request [as _callback] (/usr/lib/node_modules/homebridge-homeassistant-schmittx/index.js:107:7)
    at Request.self.callback (/usr/lib/node_modules/homebridge-homeassistant-schmittx/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-homeassistant-schmittx/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-homeassistant-schmittx/node_modules/request/request.js:1083:12)`

**Comment by schmittx** [comment]
This project is no longer maintained, I recommend you use the native Home Assistant integration for HomeKit ([link](https://www.home-assistant.io/integrations/homekit/)) as it provides more functionality at this point.
